### ISSUE TITLE
Move all artifact archiving to azure blobstorage

### ISSUE THREAD

**Issue by mmitche** [dotnet/dotnet-ci#18]
Requires a couple things.  Need to be able to tar/zip the artifacts, and requires Azure's artifact plugin has an "excludes".

This could alternatively be done in scripting.

**Comment by jasonwilliams200OK** [comment]
Perhaps something like: https://github.com/mapbox/node-pre-gyp. We identified some Azure limitations with @springmeyer for this kind of thing: https://github.com/mapbox/node-pre-gyp/issues/134. AWS however provides an excellent support. For example, the releases artifacts of all repositories on GitHub get stored in AWS seamlessly (both via web and API), but Azure is more focused on overly-complicated enterprise scenarios rather than making it easier for hacking 101 use cases like these.
Related: https://github.com/Azure/azure-content/issues/2432.

**Comment by mmitche** [comment]
@jasonwilliams200OK Thanks for the pointers.  Since all the rest of the stuff is in Azure already I think it makes sense to keep it there.  Anyways, much of the required changes noted above have been made to the plugin.  There are a couple other issues that we run into, more on the Jenkins side:

Right now it's not a seamless replacement for the built in archiving Jenkins has (ideally this would just be a different storage location).  You could make it that, but the problem is that given the way the archiving works, a lot of network traffic would go from store->server->node rather than store->node, which is actually what you want.
