### ISSUE TITLE
Warning: (combinednetci.groovy, line 558) pullRequest is deprecated

### ISSUE THREAD

**Issue by dilijev** [dotnet/dotnet-ci#417]
`Warning: (combinednetci.groovy, line 558) pullRequest is deprecated`

Seems to be coming from the Groovy code pasted in from the dotnet-ci repo

```
    def private static addGithubPRTriggerImpl(def job, String branchName, String contextString, String triggerPhraseString, boolean triggerOnPhraseOnly, boolean permitAllSubmittters, Iterable<String> permittedOrgs, Iterable<String> permittedUsers) {
        job.with {
            triggers {
                pullRequest {                         // <-- this line
                    useGitHubHooks()
```

**Comment by mmitche** [comment]
Yeah this is because the built in support in the job DSL plugin for the PR builder is deprecated.  It has moved into the PR builder itself.  That's actually why there are workarounds in the local job gen script exist in the first place (it uses a standalone jar and knows nothing about individual plugins)

**Comment by mafei071111** [comment]
mafei071111
