### ISSUE TITLE
dci-ub-fbld-5 may not have all the LLDB stuff installed?

### ISSUE THREAD

**Issue by ellismg** [dotnet/dotnet-ci#51]
Builds of coreclr on this machine are failing like this:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_linux_release/729/console

Looks like it hasn't done a clean coreclr build in a while:

http://dotnet-ci.cloudapp.net/computer/dci-ub-fbld-5/builds

**Comment by mmitche** [comment]
Looking into it, though it did a clean build on the 13th.

**Comment by mmitche** [comment]
@ellismg Looks like this was because of the way I changed a couple jobs (well, this one and the buildtools repo) to parameterize the repo URL.  It looks like it doesn't replace the parameter with the default when matching the GitHub POST with the project's push URL.  Since it's not critical, I removed that bit for now.  That does mean something bad got checked in over the weekend though.

**Comment by mmitche** [comment]
You're right, it wasn't installed on that machine (only).  Fixed.

**Comment by ellismg** [comment]
Thanks!
